### ISSUE TITLE
Validate all entity fields

### ISSUE THREAD

**Issue by phelipealves** [souagrosolucoes/postgresql-validate-json-fields#2]
We need use this extension to validate both fields from the `custom_fields` column and those from the entity.

Ex:

```
CREATE TABLE users (
    "id" serial NOT NULL,
    "name" character varying(256) NOT NULL,
    "custom_fields" jsonb NOT NULL,
    CONSTRAINT "user_id" PRIMARY KEY ("id")
);
```

Validate the field `id`, `name` and all fields contained in `custom_fields`.

**Comment by vnmedeiros** [comment]
one way to validate data is to use a constraint on specific table, per example:

https://github.com/souagrosolucoes/postgresql-validate-json-fields/commit/d709310e131f26fd91e178ffbdbe08ee50ec1c75
