### ISSUE TITLE
Field types

### ISSUE THREAD

**Issue by phelipealves** [souagrosolucoes/postgresql-validate-json-fields#3]
# Field types
- [x] **numeric** (regex: `^(([0-9]*)|(([0-9]*)\.([0-9]*)))$`)
- [x] **email**  (regex: `^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$`)
- [x] **timestamp**  (regex: `^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(([+-]\d\d:\d\d)|Z)?$`
- [x] **date** (regex: `^\d\d\d\d[- \/.](0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])$`)
- [x] **url** (regex: `^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$`)
- [x] **phone**

**Comment by vnmedeiros** [comment]
Hi @phelipealves 
the possibles "primitive types" was defined as enum in:
https://github.com/souagrosolucoes/postgresql-validate-json-fields/blob/2497a57018560c7d3bffeb6f23d00e9574bc6788/01-DDL.sql#L68

the validation of content is created in table `metadata fields` over "primitive types"
