### ISSUE TITLE
Slug is not unique

### ISSUE THREAD

**Issue by phelipealves** [souagrosolucoes/postgresql-validate-json-fields#4]
The _slug_ field of **registered_fields** is not **unique** and maybe it can be used with the same name by another table.

https://github.com/souagrosolucoes/postgresql-validate-json-fields/blob/master/DDL.sql#L72

**Comment by vnmedeiros** [comment]
https://github.com/souagrosolucoes/postgresql-validate-json-fields/commit/2497a57018560c7d3bffeb6f23d00e9574bc6788
